### ISSUE TITLE
Programming 8ch relay

### ISSUE THREAD

**Issue by DaF0xishere** [me365xyz/pico-ctrl-dev#1]
So I bought an eight channel relay that came with a Pico w and I'm having a really hard time getting it to work I can't seem to program it with the Pico I might just be dumb and not understand it or haven't learned that much yet but m just going with I can't figure out directions even simple ones or so my parents say haha. I could sure use anyone's help please I need to be able to program the relay to turn on and off at certain time for the day and for certain periods of time and then also manually turn them on and off and then I also need to  hooked up to sensors to check for moisture to turn a relay on and off It's basically for a garden project. Here is a link to the relay device
https://www.waveshare.com/wiki/Pico-Relay-B
But any help would be great. Thanks for atleast reading this.

**Comment by aarnas** [comment]
This tutorial is out of scope of current project as it is codding with Pico C/C++ SDK that is a bit trickier.
Current project is compiled MicroPython with some extra features. To set up the relay, you need to look for tutorial using MicroPython or look for library ([this for example](https://github.com/balance19/micropython_DS3231)) to use.
